---

name: PR

on:
  pull_request:
    types: [opened, synchronize]


jobs:
  snapshot:
    name: "Static snapshot"
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/gen_static_website
        id: 'gen_static_website'
      - name: show files
        run: |
          ls -lan
